### PR TITLE
implement a simple game logic loop with setInterval

### PR DESCRIPTION
**Pull request by markx**
## Related issue/feature
#39 
## Description of the changes proposed in the pull request
- Add a simple simple game logic loop with `setInterval`
- Stop calling `tick` in `render`

### CODE REVIEW

**Comment by markx** [comment]
Also can we rename `tick` to `update`? It seems to be a convention to have `update` and `render`.

**Comment by TyrealGray** [comment]
I think this issue is causing by  requestAnimationFrame. So setInterval will similar to requestAnimationFrame, even though setInterval could run in the background. I don't think setInterval is consistent, and it is inferior to RAF for animation purposes, so I wouldn't use it in any case.

**Comment by TyrealGray** [comment]
I think we should look at the direction of nwjs or Chromium setting, because we will running game in the nwjs client.

**Comment by markx** [comment]
Rendering is still done by RAF. This PR only changes the game logic loop.

**Comment by TyrealGray** [comment]
@markx `tick` function is triggering in each frame during the animation, and `tick` function actually **is** related to animation process. You can check Character class to see why.

The differences between `onRender` and `tick` function are that `onRender` is associated with `bindRender` in order to let developer add additional feature outside of the scope.

**Comment by markx** [comment]
Oh I see. So `tick` is dealing with both game logic updating and rendering. It needs a bigger refactoring to separate them.

A hack on the RAF is easier to do, but I think if you want to move the game loop to server later, you might still need to do this refactoring anyway.

I'll create a new PR for this issue.

**Comment by TyrealGray** [comment]
@markx only dealing with animation render logic. 

**For example:**
`setPosition` could be used by animation logic and game business logic (or server side), but like `playWalk` function should be never triggered by server.

**Pull request closed without merging**
