### PR TITLE
add a on screen console panel for debug #71

### PR DESCRIPTION
**Pull request by Siubaak**
## Related issue/feature

The pr is related to issue #71 and add a console panel on screen for the debug requirement of client

## Description of the changes proposed in the pull request

Add a OnScreenConsole class in file LOMS/src/util/errorUtil.js and export its singleton instance oConsole.

The oConsole overwrites the log, warn and error method of console, and it has four public methods enable, disable, show and hide.

If the oConsole is enabled, just use console.log, console.warn and console.error to print the log on the on screen console panel. If disabled, all three native console methods will be back.

## The person responsible for reviewing proposed changes

someone

### CODE REVIEW

**Comment by TyrealGray** [comment]
BTW, some eslint error is in CI build.

**Comment by Siubaak** [comment]
@TyrealGray lol. I forgot to run lint and miss several semicolon. Maybe we need to remove the rule of no-console 'cause there two needed console statements at line 81, 82 of errorUtil.js.

**Comment by TyrealGray** [comment]
Console.error is allowed, log is not needed ATM I think.

**Comment by TyrealGray** [comment]
@Siubaak feel free to merge it by yourself for your first RP 👍

**Pull request merged**
